name: advikdemo
on: 
 workflow_dispatch:
  inputs:
    envinorment:
     description: this is info demo
     required: true
     default: dev
     type: choice
     options:
       - dev
       - qa
       - test
    tags:
     description: this is demo
     required: true
     default: 1.0.0
   


jobs:
  advikdemo:
   runs-on: ubuntu-latest
   steps:
     - name: run advikdemo
       run: echo " deploy the ${{inputs.tags}}application ${{inputs.envinorment}}"
   
